compressionLevel: mixed

nodeLinker: node-modules

plugins:
  - checksum: b3b00465cee9a55ea92b7555876084a6dbfb4b9dd2ce7617a0bca1c138dec6b33befabdff7f4035b2a2ad70d59a05dad3a8faf3a34d3bec21fa7949a497fdf48
    path: .yarn/plugins/@yarnpkg/plugin-backstage.cjs
    spec: "https://versions.backstage.io/v1/releases/1.47.2/yarn-plugin"

yarnPath: .yarn/releases/yarn-4.9.2.cjs
