compressionLevel: mixed

nodeLinker: node-modules

plugins:
  - checksum: b613ebeede2fffe7e36d1d601014dbabc7cc61453ed942975c92152f6563a9ed3e3e3659b20e32f601b2062bbe4bfc53314dcace9d7c600ab5dd11d39a4e2f30
    path: .yarn/plugins/@yarnpkg/plugin-backstage.cjs
    spec: 'https://versions.backstage.io/v1/releases/1.43.3/yarn-plugin'

yarnPath: .yarn/releases/yarn-4.9.2.cjs
