compressionLevel: mixed

nodeLinker: node-modules

plugins:
  - checksum: ae08ece83681cc6d217ebb53d9e00a06ea215383f34af0681a05da5720e018a6b0d98012112f9368e9fe2328b19919baba37ada25f46c4614b894765a9338db9
    path: .yarn/plugins/@yarnpkg/plugin-backstage.cjs
    spec: "https://versions.backstage.io/v1/releases/1.54.1/yarn-plugin"

yarnPath: .yarn/releases/yarn-4.9.2.cjs
