compressionLevel: mixed

nodeLinker: node-modules

plugins:
  - checksum: 8af7b3f2d7d19cacc7a3712f871efcb6208ba283a1f532260b0cba80c2cb66ed772b207b5ba41b8c5d64dd8d5e0c0e15bbb445bd14afac491712965211ba027c
    path: .yarn/plugins/@yarnpkg/plugin-backstage.cjs
    spec: 'https://versions.backstage.io/v1/releases/1.42.5/yarn-plugin'

yarnPath: .yarn/releases/yarn-4.9.2.cjs
