nodeLinker: node-modules

plugins:
  - checksum: 3f0f3e2debfccaa85999007e42aed55409ba895e71bf2cfde4cf49210472b17d007dfefdffd38fc3685ceadaa842b5673cac68252766aec50b37837c8b086dfb
    path: .yarn/plugins/@yarnpkg/plugin-backstage.cjs
    spec: "https://versions.backstage.io/v1/releases/1.40.2/yarn-plugin"

yarnPath: .yarn/releases/yarn-4.9.2.cjs
