compressionLevel: mixed

nodeLinker: node-modules

plugins:
  - checksum: a7960e90b20fe64de29d899d907dd9d539f4111357d84ce89eab20c01ea2941d4d4ee2a569d220be2f92f93d63cee18b85a6273cbb74980564fb80f7ee7c64d2
    path: .yarn/plugins/@yarnpkg/plugin-backstage.cjs
    spec: "https://versions.backstage.io/v1/releases/1.44.2/yarn-plugin"

yarnPath: .yarn/releases/yarn-4.9.2.cjs
